### ISSUE TITLE
APPLIED STYLES NOT APPLIED IN SHAPEFILE GENERATION

### ISSUE THREAD

**Issue by bwmoths** [burkmarr/QGIS-Biological-Recording-Tools#11]
Applied styles files used to produce the TEMP layers do not seem to be applied to any shapefiles generated by the 'Output options' section. 
I would like to use the QGIS2WEB plugin to produce >1200 species distribution maps but if the shapefile output does not have the STYLES applied, these styles will have to be added individually to all of the shapefiles !
Martin Love

p.s. I don't  seem to be able to get QGIS to apply STYLES to batches of layers (which might mitigate the problem) only individually !

**Comment by burkmarr** [comment]
Yes I've thought about this before and it seems like a reasonable feature request. I'll add it to the list of tasks to consider for the next release.

**Comment by bwmoths** [comment]
Thank you Rich, I look forward to the next release with anticipation (He He) !
