### ISSUE TITLE
problem saving TEMP layer to shp

### ISSUE THREAD

**Issue by DiemerV** [burkmarr/QGIS-Biological-Recording-Tools#14]
Dear Rich,

My colleague Kris Boers contacted you earlier about the use of your plugin 'TomBio Tools' for UTM grids in Belgium. This plugin saves us a lot of time, so thank you for that! 
But I noticed a bug in the plugin. When trying to save the TEMP files as a shape file I get an error that zero objects are saved. Only an empty shapefile is generated. The error is that the GridRef cells are empty. So when I entered a dummy value (1) for every cell the problem was solved. But this means I can't use the output function Format=shapefile and automatically save all generated TEMP layers to shp, unless I manually fill the GridRef column in every TEMP layer. Would it be possible to fix this in a next update of the plugin? 

![image](https://user-images.githubusercontent.com/32329403/30911380-9f8280a2-a388-11e7-9c36-c67d6f3853b3.png)

Best regards,
Diemer

**Comment by burkmarr** [comment]
Thanks Diemer - I will look into this.

**Comment by DiemerV** [comment]
Thanks!

**Comment by burkmarr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [problem saving TEMP layer to shp](https://trello.com/c/iHyy8crI/17-problem-saving-temp-layer-to-shp)

**Comment by burkmarr** [comment]
I reproduced this with version 2.8.0 but when I came to address the problem with version 3.0.0, I cannot reproduce it. What happens now (and what should have happened before) is that for atlas maps generated from x/y coords, a 'gridref' value of 'x#y' is added to the column.

**Comment by DiemerV** [comment]
Hi Rich. Thanks for adressing this issue again. I'm working with QGIS 2.18. Is it possible version 3.0.0 of TomBiotools isn't available (yet) for QGIS 2.18? I tried to update the plugin, but 2.8.0 seems to be the most recent available version. In this version records are empty for 'gridref'.

**Comment by burkmarr** [comment]
Hello again! The version I am working on at the moment will only work with QGIS V3. Do you have plans to install version 3 of QGIS? (You can always run v2.18 and v3.0 side-by-side on the same computer.).

**Comment by DiemerV** [comment]
OK. Just installed QGIS 3.0.1 (Girona). Now waiting for your plugin to become available. :-)

**Comment by burkmarr** [comment]
Great. I'm hoping it will be published before the end of next week.
