### ISSUE TITLE
Map records as squares displaces 10 figure grid refs by 0.5 metres

### ISSUE THREAD

**Issue by burkmarr** [burkmarr/QGIS-Biological-Recording-Tools#16]
From an email from Eric Fletcher (Cheshire Record)

>>>
I am not sure why I haven’t noticed this before now, but it seems that when I have imported Rec6 data into QGIS using TomBio it has displaced the 10 figure squares to the north and east by half a metre, or so it would seem. All other resolution data seems to display correctly. I have been using a dataset for the zoo estate and it contains 4, 6, 8 and 10 figure references.

I have attached an image that gives an example of the issue.
<<<
![chester zoo estate_species distribution map zoomed_oct 2017](https://user-images.githubusercontent.com/9275178/31677663-7783dd54-b363-11e7-90c1-0086083a784e.jpg)

**Comment by FletcherEric** [comment]
Hi Rich, thanks for this. It isn't critical for us at the moment, we are just producing some general distribution maps and they are at a fairly coarse resolution.

**Comment by burkmarr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Map records as squares displaces 10 figure grid refs by 0.5 metres](https://trello.com/c/VWFJJYvg/15-map-records-as-squares-displaces-10-figure-grid-refs-by-05-metres)

**Comment by burkmarr** [comment]
Fixed for release 3.0.0.
