### ISSUE TITLE
New filter (spp group) for NBN Atlas tool

### ISSUE THREAD

**Issue by MAPlanGo** [burkmarr/QGIS-Biological-Recording-Tools#17]
Hi Rich. As discussed, I would like to request an enhancement to the NBN Atlas tool - an additional filter to allow user to return and download data for a group of species, e.g. on a designated list or user-defined species list. I think this would be of use for many TomBio users.  It looks like it should be supported by the NBN Atlas webservices: https://api.nbnatlas.org/ in one way or another!

**Comment by burkmarr** [comment]
Thanks Matt. I will review this the next time I do any major work on the tool. (That might well be when I look to do a version for QGIS 3.)

**Comment by burkmarr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New filter (spp group) for NBN Atlas tool](https://trello.com/c/Fjpf8DUL/14-new-filter-spp-group-for-nbn-atlas-tool)
