### ISSUE TITLE
CONVERTING GRID LAYER TO SHAPEFILE

### ISSUE THREAD

**Issue by bwmoths** [burkmarr/QGIS-Biological-Recording-Tools#20]
QGIS 3.0 - Not sure if I'm doing something wrong but, trying to convert an OSGR Tool, grid layer to a shapefile using 'Layer - Save As' produces an error as in the attached.
Regards
Martin
![15-05-2018 09-40-48](https://user-images.githubusercontent.com/27619809/40046931-9f3eb5da-581d-11e8-86b3-134fe99f6064.png)

**Comment by bwmoths** [comment]
Thanks Rich, spot on, all fixed now ! Sorry to trouble you !

**Comment by burkmarr** [comment]
No worries Martin - that's what this forum is for (as well as tracking bugs, making feature requests and all the rest).
