### ISSUE TITLE
Problem installing QGIS plugin.

### ISSUE THREAD

**Issue by AElletson** [burkmarr/QGIS-Biological-Recording-Tools#25]

**Comment by AElletson** [comment]
I run a mac with version 10.5 and have QGIS 3.18 and am having difficulty installing the plugin.  I can not find the plugin on the QGIS repository.  maybe I am looking in the wrong place?

Help much appreciated

**Comment by burkmarr** [comment]
Hi AElletson,

I'm not aware of any plugin installation problems with Mac. Two questions...

Are you using QGIS 2.18 or version 3 point something? (There is no version 3.18).

If you go to the plugin manager and view 'All' plugins. Can you list for me all those you can see that start with the letter T?

Rich

**Comment by burkmarr** [comment]
Great - I'm glad you got it sorted Anthony.

Rich
