### ISSUE TITLE
Importing CSV using 3.4.4-Madeira

### ISSUE THREAD

**Issue by Royt65** [burkmarr/QGIS-Biological-Recording-Tools#30]
Hi Rich. I've just tried opening a csv with 3.4.4-Madeira having upgraded QGIS earlier this week and it doesn't seem to open it. It also gives me no indication that anything has failed too. I've just tried opening the same file using QGIS 2.1.18 and it opens fine. Any suggestions? Thanks

**Comment by burkmarr** [comment]
Do you mean via the FSC plugin Biological Records tool?

**Comment by Royt65** [comment]
Yes. Sorry I do mean this tool. Thanks

**Comment by burkmarr** [comment]
I can't reproduce the problem on 3.4.4. Can you list the steps your are taking?

**Comment by Royt65** [comment]
Sorry Rich I've just tried importing it from a copy of the .csv not stored on my desktop and it worked. I spoke to someone else and they had the same issue with files stored on their desktop. Thanks for your swift reply and sorry to bother you.

**Comment by burkmarr** [comment]
Okay no worries.

**Comment by Royt65** [comment]
One quick question related to FSC plugin Biological Records tool. Does it have a limit regarding the amount of records it can handle or is this only determined by the limit the size of the .csv ? My understanding csv files don't have a limit whereas Excel is limited to a million records. What's the biggest file you've ever used with the plugin?

**Comment by burkmarr** [comment]
The most I've used it with is about 800,000. It worked but performance was slow. We are looking at direct connections to DBs for large datasets.

**Comment by Royt65** [comment]
Thanks Rich. I'll try it with 300,000 records. Connecting to a database would help as long at its easy to do. Often databases are locked down too. Thanks for your help.
