### ISSUE TITLE
QGIS PRINT COMPOSER AND TOMBIO COMPOSER IMAGE #TAXON# LINK 

### ISSUE THREAD

**Issue by bwmoths** [burkmarr/QGIS-Biological-Recording-Tools#9]
Has the link between the QGIS Print Composer and the TOMBIO Composer Image output brocken ? I wanted to print some distribution maps using the TOMBIO composer image output that used to work fine but now instead of printing the Taxon name as in the CSV file the distribution map shows #TAXON# etc.
This seems to have happened after upgrading QGIS to V 2.18.6 and TOMBIO to the NBNatlas version !

**Comment by burkmarr** [comment]
I don't think it is - just tested with QGIS 2.18.2. I noticed that you used the token #TAXON# but to use the name of the taxon - derived from the name of the shapefile - you need to use the token #name#. You can use other tokens corresponding to column names in a supplementary metadata CSV file. If you were trying to do the latter, let me know.

**Comment by bwmoths** [comment]
Hi Rich, is the "Taxon Metadata Layer" section new ? I don't seem to remember it being there before or indeed ticking it ! Could be senile demetia of course. However, selecting it restores the link to add #column header# etc., data for a TEMP layer to a QGIS Print Composer - Tombio Composer Image output !!
So back to normal I think, sorry to trouble you !
Martin Love

**Comment by burkmarr** [comment]
Hi Martin (I didn't realise it was you!). It was new with version 2.6.0 of the plugin. Before that you could only use the #name# token, so if you remember using tokens corresponding to headers in a supplementary  CSV metadata file, then this is what you used. It's documented here: http://www.tombio.uk/qgisbiorecstool (at the end of the page just before the video tutorials).

**Comment by bwmoths** [comment]
Hi again, I must have used it then ! Definitely senile dementia !!!!!!! I now have >1200 species dist' maps to output so rue the fact that one has to manualy start each output. Ho Hum, numb brain and sore finger coming !
Best wishes
Martin

**Comment by burkmarr** [comment]
I'm rather hoping that version three of QGIS might help me overcome that last problem you mention. But when version three comes out, it will likely require a complete rewrite of the plugin, so it won't happen any time soon.
